### PR TITLE
Do not call recentf-mode in :config stage of counsel package.

### PR DESCRIPTION
**Pull request by a-sk**
Right now, recentf save file gets overwritten on every emacs restart.

### CODE REVIEW

**Comment by justbur** [comment]
Why would this happen by just calling the mode function?

**Comment by a-sk** [comment]
I suspect that this is happening because `spacemacs-base/init-recentf` is executed
after `spacemacs-base/init-counsel`.
`spacemacs-base/init-recentf` changes `recentf-save-file` and by calling `(recentf-mode)` here, `recentf-mode` initialises with the default empty `recentf-save-file`.
I'm not quite sure why Spacemacs's `recentf-save-file` gets overwritten, but by simply removing this line I fixed the issue for me.

You can try to reproduce it by yourself:
* open Emacs
* go to any file
* close Emacs
* visited file should be in `~/.emacs.d/.cache/recentf` (if you didn't manually change `recentf-save-file`)
* open Emacs
* try to use `ivy-recentf`: in my case, the list is empty
* close Emacs once again
* `~/.emacs.d/.cache/recentf` file is empty now

**Comment by justbur** [comment]
Ok I was noticing something weird with recent files but this sounds like a
bug to me in how spacemacs is doing things.

**Comment by a-sk** [comment]
Maybe we could add `recentf-mode` call to ivy-mode-hook in `spacemacs-base/init-recentf` function,
as it's done for `find-file-hook`, what do you think?
I tested and it's working for me.

**Comment by justbur** [comment]
Sure that sounds better at least. When I get a chance I'll try to figure
out what's happening with this file.

**Comment by a-sk** [comment]
Ok, sounds great, thanks.

**Comment by justbur** [comment]
Thanks for your help

**Pull request merged**
